### ISSUE TITLE
Issue with TB 68.3

### ISSUE THREAD

**Issue by justmelly** [TB-throwback/LookOut-fix-version#51] opened 2020-01-20 20:35 UTC
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Debian 8
* Thunderbird version number: 68.3
* 64 bit/32 bit: 64bit
* LookOut (fix version) version number: 2.0

# Expected Behavior

I would expect that the plugin would allow for winmail.dat files to show the files contained within the attachment

# Current Behavior

The current behavior does not show the current files within winmail.dat. It only shows the actual winmail.dat file

# Failure Information (for bugs)

I enabled debugging for Lookout but it doesn't show anything related to the add-on itself

*NOTE: I tried recreating this on another machine and could not do it. We set up a Debian 8 machine (Same OS level), installed the same version of Thunderbird & Lookout and it works. I can't for the life of me figure out why these specific set of machines won't work. We even tried recreating the Thunderbird profile itself to make sure something within it was not causing the issue and nothing. I also compared the prefs.js from the working system to a non working system and there's no differences.

Any other ideas??

**Comment by dugite-code** [comment] 2020-01-21 00:11
Duplicate of #50 

Unfortunately I haven't been able to replicate this issue at all. For some reason the start-up [listener](https://github.com/TB-throwback/LookOut-fix-version/blob/master/src/chrome/content/lookout.js#L616) is failing randomly. I'm not sure why.

**Closed by dugite-code** 2020-01-21 00:11 UTC
