### ISSUE TITLE
Can't drag and drop the attachments

### ISSUE THREAD

**Issue by jnmills** [TB-throwback/LookOut-fix-version#84] opened 2021-12-31 09:16 UTC
Running 4.3 Updated 29 Dec 2021 on TB 91.4.1 (64 bit) / Windows 10 21H2 (Build 19044.1415)
I received a winmail.dat with 3 included files.  Lookout correctly presented them, but when I drag and dropped each of the 3 files, instead of their individual names and content I got 3 copies of winmail.dat.<n>, each of the same size.

Saving the attachments instead did work correctly.

**Comment by dugite-code** [comment] 2022-02-16 01:54
Duplicate of #56

@jnmills drag and drop support had to be removed as it was a bit of a hacky work-around. Unfortunately only the save and save all buttons are currently supported.

**Closed by dugite-code** 2022-02-16 01:54 UTC
