### ISSUE TITLE
Update to TB 68.6 and not working

### ISSUE THREAD

**Issue by LeslieDesser** [TB-throwback/LookOut-fix-version#60] opened 2020-03-17 13:55 UTC
Updated TB today.

* Operating System: W10 Pro
* Thunderbird version number: 68.6.0
* 64 bit/32 bit: 32
* LookOut (fix version) version number: Latest

# Expected Behavior

winmail.dat be shown as separate attachments

# Current Behavior

winmail.dat appears as a single attachment.

**Comment by dugite-code** [comment] 2020-04-02 07:08
Probably a duplicate of https://github.com/TB-throwback/LookOut-fix-version/issues/50

Please set the option `Tools -> Options -> Display -> Advanced -> Open messages` in: to `A new tab` instead of `A new message window`

**Closed** 2020-06-08 17:04 UTC
Labels: wontfix
